### ISSUE TITLE
点击侧边栏选项页面没有响应

### ISSUE THREAD

**Issue by DangoSky** [FEMessage/blog#2]
你好，我发现点击侧边栏选项后虽然页面url改变了，但页面并没有得到相应的跳转，需要刷新页面之后才能恢复正常（如下图）。我在几台电脑上实验后发现都是如此，但我clone仓库在本地打开却发现并没有这个问题。我不知道该怎么解决这个异常，所以无法给出相关的PR。

![1](https://user-images.githubusercontent.com/42209399/58223701-5e539300-7d4d-11e9-97b7-b1a82a298df5.gif)

**Comment by levy9527** [comment]
你好，感谢你的反馈。已经解决了 #3
